### ISSUE TITLE
The program stops 

### ISSUE THREAD

**Issue by Adelax92** [SkyAlumny/MyPrefire-Cracked#1]
When u put on the program switch off in 1 second u cant use it.

**Comment by Adelax92** [comment]
![1](https://github.com/SkyAlumny/MyPrefire-Cracked/assets/92597817/d2951557-56ba-46fb-b160-90731f9dadbe)

**Comment by SkyAlumny** [comment]
Noticed that, will be fixed soon!

**Comment by mrhston33** [comment]
whats the predicted date on realeasing the fix

**Comment by SkyAlumny** [comment]
Lets see, the next days.
